Bug 2069691 - gfx: Move RenderSourceNLRS's destructor out of line for C++23 compatibility. r=gfx-reviewers,lsalzman
C++23 P2448R2 [1] relaxed the requirements for constexpr destructors.
In C++23 mode, Clang makes RenderSourceNLRS's defaulted destructor
automatically constexpr. Clang defines that destructor in NativeLayer.h
with only a forward declaration of gl::MozFramebuffer.

Defining RenderSourceNLRS's destructor instantiates the destructor of
its UniquePtr<gl::MozFramebuffer> member. Its default deleter requires
MozFramebuffer to be complete, so libc++'s completeness check fails.

To resolve this, move RenderSourceNLRS's destructor to NativeLayer.cpp,
where MozFramebuffer.h provides the complete type. This avoids adding
its GL header dependencies to NativeLayer.h.

[1] https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2448r2.html

MacOSX26.4.sdk/usr/include/c++/v1/__memory/unique_ptr.h:75:19: error: invalid application of 'sizeof' to an incomplete type 'mozilla::gl::MozFramebuffer'
   75 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete type");
      |                   ^~~~~~~~~~~
obj-macos/dist/include/mozilla/layers/NativeLayer.h:264:7: note: in instantiation of member function 'std::unique_ptr<mozilla::gl::MozFramebuffer>::~unique_ptr' requested here
  264 | class RenderSourceNLRS : public profiler_screenshots::RenderSource {
      |       ^
obj-macos/dist/include/mozilla/layers/NativeLayer.h:264:7: note: in implicit destructor for 'mozilla::layers::RenderSourceNLRS' first required here
obj-macos/dist/include/mozilla/layers/NativeLayer.h:22:7: note: forward declaration of 'mozilla::gl::MozFramebuffer'
   22 | class MozFramebuffer;
      |       ^

Differential Revision: https://phabricator.services.mozilla.com/D323893